version: '3'

services:
  web-server:
    build: # Dockerfile path relative to this file
      context: .
    ports: # Map ports on host (computer) to ports in container
      - 8000:8000 # host : container
    volumes: # Map hard drive from host (computer) to drive in container
      - ./RapidResume:/app
  
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"