# Generated by Django 4.2.3 on 2023-07-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_builder", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Random",
        ),
    ]
