# Generated by Django 4.2.3 on 2023-09-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_remove_userprofile_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='template',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
