# Generated by Django 4.2.3 on 2023-10-11 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0004_remove_resume_template_delete_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.resume'),
        ),
    ]
